// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcpF71sRM5Ea_zfQqJBjCZtI195PyxK_A',
    appId: '1:944428758195:web:02b419de986644418aacc6',
    messagingSenderId: '944428758195',
    projectId: 'uas-poscare',
    authDomain: 'uas-poscare.firebaseapp.com',
    storageBucket: 'uas-poscare.firebasestorage.app',
    measurementId: 'G-L7XTLGG4ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhXTbxMhMBapjC_LYm1RJPNcLfCjv0Tc',
    appId: '1:944428758195:android:d354ea90321d4b7c8aacc6',
    messagingSenderId: '944428758195',
    projectId: 'uas-poscare',
    storageBucket: 'uas-poscare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3VKXOtFo74EHDjD2xzcKYOdXWcyw7aXs',
    appId: '1:944428758195:ios:f75ce890c8e7e16a8aacc6',
    messagingSenderId: '944428758195',
    projectId: 'uas-poscare',
    storageBucket: 'uas-poscare.firebasestorage.app',
    iosBundleId: 'com.example.poscare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3VKXOtFo74EHDjD2xzcKYOdXWcyw7aXs',
    appId: '1:944428758195:ios:f75ce890c8e7e16a8aacc6',
    messagingSenderId: '944428758195',
    projectId: 'uas-poscare',
    storageBucket: 'uas-poscare.firebasestorage.app',
    iosBundleId: 'com.example.poscare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcpF71sRM5Ea_zfQqJBjCZtI195PyxK_A',
    appId: '1:944428758195:web:f99a9a9acfae182f8aacc6',
    messagingSenderId: '944428758195',
    projectId: 'uas-poscare',
    authDomain: 'uas-poscare.firebaseapp.com',
    storageBucket: 'uas-poscare.firebasestorage.app',
    measurementId: 'G-B09H9XJJ5C',
  );
}
